baseURL = "https://www.gheychi.net/"
title = "نشر قیچی"
author = "نشر قیچی"
copyright = " قیچی / هزارُچهارصدُیک "
paginate = 10
description = "پروژه ادبیات الکترونیک نشر قیچی"
languageCode = "fa"
DefaultContentLanguage = "fa"
direction = "RTL"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "origin-hugo-theme"
textFontFamily = "roozname"
headingFontFamily = "roozname"

[params]
  description = ""
  featured = false
  cssonly = false


  [params.socials]
    facebook = "https://www.facebook.com/gheychi.net"
    twitter = "https://www.twitter.com/gheychinet"
    instagram = "https://www.instagram.com/gheychinet"
    youtube = ""
    github = "https://www.github.com/nimabeh/30zermbot"
    gitlab = ""
    linkedin = ""
    slack = ""
    stackoverflow = "RSS"
    medium= ""

[menu]


[[menu.main]]
  identifier = 'about'
  name = 'حمایت'
  pre = "<i class='fa fa-heart'></i>"
  url = "https://www.paypal.com/donate/?hosted_button_id=9TTEZWK4DGFNJ"
  weight = -110
[[menu.main]]
  name = 'درباره'
  post = "<span class='alert'>New!</span>"
  pre = "<i class='fa fa-road'></i>"
  url = '/about/'
  weight = -120



[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    style = "github"
    tabWidth = 4

[markup.goldmark.renderer]
unsafe = true


